apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/mabusaa/argocd-example-apps-private.git
  password: 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
  username: my-token