apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-1
  namespace: argocd
# spec:
#   generators:
#   - clusters: {}
#   template:
#     metadata:
#       name: '{{name}}-release-name'
#       namespace: argocd
#       labels:
#         app: any
#         cluster: local-cluster
#         owner: nobody
#         parent: release-name
  spec:
    generators:
    - clusters:
        selector:
          matchLabels:
            stage: dev
          matchExpressions:
          - key: type
            operator: In
            values: ["none"]
    spec:
      project: default
      source:
        repoURL: https://github.com/wreed4/example-helm
        targetRevision: master
        path: .
      destination:
        name: '{{name}}'
        namespace: argocd
    syncPolicy:
      preserveResourcesOnDeletion: true
    # spec:
    #   project: default
    #   source:
    #     repoURL: https://github.com/AditiNagar31/argocd-example-apps.git
    #     targetRevision: master
    #     path: guestbook
    #   destination:
    #     server: '{{server}}'
    #     namespace: guestbook-1
    #   syncPolicy:
    #      syncOptions:
    #       - CreateNamespace=true
